          _tile(context, Icons.location_on_outlined, 'Addresses',
              () => context.push('/addresses')),
          _tile(context, Icons.credit_card_outlined, 'Payment methods',
              () => context.push('/payment-methods')),
          _tile(context, Icons.notifications_none_rounded, 'Notifications',
              () => context.push('/notifications')),
          _tile(context, Icons.help_outline_rounded, 'Help & support',
              () => context.push('/help')),